version: '3.8'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=lemonade
      - POSTGRES_PASSWORD=supersecureadminpassword
      - POSTGRES_DB=taskresults
    ports:
      - "5432:5432"