version: '3.8'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=lemonade
      - POSTGRES_PASSWORD=supersecureadminpassword
      - POSTGRES_DB=playqueue
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql